config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'   
  } 
  root to: "top_pages#home"
  get  "top_pages/help"
  get  "top_pages/message"

  resources :users
  resources :trainings
  resources :events, only: [:new, :create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :trainings, dependent: :destroy
  has_many :events, dependent: :destroy
  validates :username, presence: true
  validates :username, uniqueness: true
  validates :email, presence: true
  validates :email, uniqueness: true
  validates :email, length: { maximum: 50 }
  validates :email, length: { minimum: 8 }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.paginate(page: 1)
  end

  def show
    @user = User.find(params[:id])
    @event = @user.events
    @trainings = @user.trainings.paginate(page: params[:page], per_page: 5)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes(user_params)
    redirect_to user_path(@user)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash.notice = "アカウントを削除しました。"
    redirect_to root_path
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
  <h2>登録情報変更</h2>
  <%= form_with model: @user, local: true do |f| %>
    <div class="row　justify-content-center">
      <div class="form">
        <%= f.label :username, "名前", class: "label" %><br/>
        <%= f.text_field :username, :size => "30*30", class: "input" %>
      </div>

      <div class="form">
        <%= f.label :email, "メールアドレス" %><br/>
        <%= f.email_field :email, :size => "30*30" %>
      </div>　

      <div class="form">
        <%= f.label :password, "パスワード" %><br/>
        <%= f.password_field :password, :size => "30*30" %>
      </div>

      <div class="form">
        <%= f.label :password_confirmation, "パスワード(確認用)" %><br/>
        <%= f.password_field :password_confirmation, :size => "30*30" %>
      </div>
    </div>
    <%= f.submit %>
    <% end %>
    <%= link_to "退会", user_path(id: current_user), method: :delete %>
</div>

app/views/users/index.html.erb
<h1>全ユーザー</h1>
<%= will_paginate %>
<ul class="users">
<% @users.each do |user| %>
  <li>
    <%= link_to user.username, user %>
  </li>
<% end %>
</ul>

<%= will_paginate %>

app/views/users/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-8">
      <% if @user.id == current_user.id %>
      <h1><%= @user.username %>のマイページ</h1>   
      <%= link_to "体温　予定の記入", new_event_path %>
      <%= month_calendar events: @event do |date, event| %>
        <%= date %>
        <% event.each do |event| %>
          <div>
            <%= event.name %>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="col-md-4">
      <h2>運動メニュー</h2></br>
      <h3><%= @user.username %>さんが考案したトレーニングメニューリスト</h3>
      <div class="paginate text-center">
        <%= will_paginate @trainings, :previous_label => ' &lt 前へ', :next_label => '次へ &gt' %>

        <% @trainings.each do |n| %>
          <ul>
            <li><%= n.title %></li>
            <li><%= n.content %></li>
          </ul>
        <% end %>

        <%= will_paginate @trainings, :previous_label => ' &lt 前へ', :next_label => '次へ &gt' %>

        <% end %>
        <h3><%= link_to "メニューの作成", new_training_path %></h3>
      </div>
    </div>
  </div>
</div>