config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'   
  } 
  root to: "top_pages#home"
  get  "top_pages/help"
  get  "top_pages/message"

  resources :users
  resources :trainings
  resources :events, only: [:new, :create, :destroy]
end

app/views/shared/_events_form.html.erb
<%= form_with(model: @event, local: true) do |f| %>
    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
  
    <div class="field">
      <%= f.label :start_time %>
      <%= f.datetime_select :start_time %>
    </div>
  
    <div class="field">
      <%= f.label :end_time %>
      <%= f.datetime_select :end_time %>
    </div>
  
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>  

app/views/shared/_footer.html.erb
<footer class="bg-info">
  <div class="border">
    <ul class="navbar-nav list-unstyled">
      <li class="nav-item ml-auto"><%= link_to "ヘルプ", "#", class: "header-item" %></li>
      <li class="nav-item ml-auto"><%= link_to "お問い合わせ", "#", class: "header-item" %></li>
    <ul>
    <%= debug(params) if Rails.env.development? %>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-info">
  <a class="navbar-brand" href="#">Health Management</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to "トップ", root_path, class: "header-item" %><span class="sr-only">(current)</span></a>
        </li>
    　</ul>
      <ul class="navbar-nav list-unstyled">
        <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "マイページ", user_path(id: current_user), class: "header-item" %><span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <%= link_to "登録情報", edit_user_path(id: current_user), class: "header-item" %></a>
        </li>
        <li class="nav-item">
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "header-item" %></a>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "ログイン", new_user_session_path, class: "header-item" %></a>
        </li>
        <li class="nav-item">
          <%= link_to "新規登録", new_user_registration_path, class: "header-item" %></a>
        </li>
      <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/shared/_shims.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>